[server]
headless = true
address = "0.0.0.0"
port = 5000

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8F0"
textColor = "#262730"
font = "sans serif"
